#!/bin/bash
usage="\nPurpose: Delete a user on OSX. Unfortunately there is no builtin script to do so on OSX, like 'deluser' for Linux/Unix.

Usage: $0 [-u <userName>]
		[<userName>]
		[-h]

-h: Display help text
-u <userName>: Delete user <userName>

Author: George Asante, https://github.com/GeorgeKA\n\n"

user='null'

while getopts ":u:h" opt
do
	case $opt in
		u)
			user="$OPTARG"
			;;
		h)
			printf "$usage"
			exit 1
			;;
		\?)
			printf "Invalid argument: $OPTARG\n"
			printf "$usage"
			exit 1
			;;
		:)
			printf "Missing an argument\n"
			printf "$usage"
			exit 1
			;;
	esac
done

if [[ $UID -ne 0 ]]
then
    printf "\nPlease run $0 as root.\n\n"
    exit 1
fi

if [ "$user" != 'null' ] # Allow for a POSIX type argument...
then
	:
elif [ "$1" != "" ] # ...and a normal command line argument
then
	user=$1
else
    printf "Try again\n-------Usage-------\n"
	printf "$usage"
    exit 1
fi

# Verify the existance of the given user
dscl . -list /users UniqueID | grep "$user"
if [ "$?" == "1" ]
then
	echo "User $user does not exist."
	exit 1
fi

# Perform the actual deletion
userGroups=$(groups "$user")
for i in $userGroups
do
	printf "Remove $user from $i\n"
	# The below sometimes returns messages about an invalid path, so I'll route the output to null. I figure dscl may do some auto group removal either when membership from certain groups is removed, or when the user is delted.
	sudo dscl . -delete /Groups/"$i" GroupMembership "$user" > /dev/null 2>&1
done
sudo dscl . -delete /Users/"$user"

if [ -d /Users/"$user" ]
then
    sudo rm -rf /Users/"$user"
fi

printf "User $user removed\n"
