#!/bin/bash
#TODO: Add support for removal from all varieties of groups
usage="\nPurpose: Delete a user on OSX. Unfortunately there is no builtin script to do so on OSX, like 'deluser' for Linux/Unix.

Usage: $0 [-u <userName>]
		[<userName>]
		[-h]

-h: Display help text
-u <userName>: Delete user <userName>

Author: George Asante, https://github.com/GeorgeKA\n\n"

user='null'

while getopts ":u:h" opt
do
	case $opt in
		u)
			user="$OPTARG"
			;;
		h)
			printf "$usage"
			exit 1
			;;
		\?)
			printf "Invalid argument: $OPTARG\n"
			printf "$usage"
			exit 1
			;;
		:)
			printf "Missing an argument\n"
			printf "$usage"
			exit 1
			;;
	esac
done

if [[ $UID -ne 0 ]]
then
    printf "Please run $0 as root.\n--------------\n"
    exit 1
fi

if [ "$user" != 'null' ] # Allow for a POSIX type argument...
then
	:
elif [ "$1" != "" ] # ...and a normal command line argument
then
	user=$1
else
    printf "Try again\n-------Usage-------\n"
	printf "$usage"
    exit 1
fi

# Verify the existance of the given user
dscl . -list /users UniqueID | grep "$user"
if [ "$?" == "1" ]
then
	echo "User $user does not exist."
	exit 1
fi

# Perform the actual deletion
sudo dscl . -delete /Users/"$user"
sudo dscl . -delete /Groups/admin GroupMembership "$user"

if [ -d /Users/"$user" ]
then
    sudo rm -rf /Users/"$user"
fi

printf "User $user removed\n"
